/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import cine.cinelugar.Sala;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JToggleButton;

/**
 *
 * @author Diego
 */
public class CreacionSala extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public CreacionSala() {
        initComponents();
        setLocationRelativeTo(null);
        botones();
    }
    
    int filas =10;
    int columnas =20;
    int largoBoton=50;
    int anchoBoton =25;
    int ejeX=20;
    int ejeY=20;
    Sala sala=new Sala(filas,columnas);
    
    public JToggleButton [][] jtBotones =new JToggleButton[filas][columnas];
    
    public void botones(){
        jtBotones= new JToggleButton[filas][columnas];
        for(int i=0;i<filas; i++){
            for(int j=0;j<columnas;j++){
                jtBotones[i][j]= new JToggleButton();
                jtBotones[i][j].setBounds(ejeX,ejeY,largoBoton,anchoBoton);
                //jtBotones[i][j].setFont hay que hacer esto
                jtBotones[i][j].setBackground(Color.BLUE);
                
                AccionBotones accion=new AccionBotones();
                jtBotones[i][j].addActionListener(accion);
                
                
                pnlBotones.add(jtBotones[i][j]);
                ejeX+=55;//separacion ejeX
                
            }
            ejeX=20; //reseteo la poss inicial
            ejeY+=30; //separacion ejeY
        }
    }
    
    public class AccionBotones implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            for(int i=0; i<filas; i++){
                for(int j=0;j<columnas;j++){
                    if(e.getSource().equals(jtBotones[i][j])){
                        if(jtBotones[i][j].isSelected()){
                            jtBotones[i][j].setBackground(Color.RED);
                            sala.getButacas()[i][j].setExiste(true);
                            sala.setCapacidad(sala.getCapacidad()+1);
                            //aumentar contador para comparar con cantidad de boletos
                        }else{
                            jtBotones[i][j].setBackground(Color.BLUE);
                            sala.getButacas()[i][j].setExiste(false);
                            sala.setCapacidad(sala.getCapacidad()-1);
                            //disminuir contador
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 720));

        background.setMinimumSize(new java.awt.Dimension(1280, 720));
        background.setName(""); // NOI18N
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        background.add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1240, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionSala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel pnlBotones;
    // End of variables declaration//GEN-END:variables
}
