/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import cine.cinelugar.Cine;
import cine.user.*;
import excepciones.CampoVacioException;
import excepciones.EmailException;
import excepciones.LongitudPasswordException;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import persistencia.Persistencia;
import validacion.Validaciones;

/**
 *
 * @author Diego
 */
public class Login extends javax.swing.JFrame {

    private final String imgCineDir = "src\\main\\images\\cinema-logo.png";
    private final String refImg = "src\\main\\images\\reflector.png";
    private final String refImg2 = "src\\main\\images\\reflector2.png";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        iniciar();
    }

    private void iniciar() {
        lblImagenCine.setHorizontalAlignment(JLabel.CENTER);
        lblReflector1.setHorizontalAlignment(JLabel.CENTER);
        lblReflector2.setHorizontalAlignment(JLabel.CENTER);

        try {
            Image img = new ImageIcon(imgCineDir).getImage();
            ImageIcon imgIcon = new ImageIcon(img.getScaledInstance(240, 230, Image.SCALE_SMOOTH));
            lblImagenCine.setIcon(imgIcon);

            Image img2 = new ImageIcon(refImg).getImage();
            ImageIcon imgIcon2 = new ImageIcon(img2.getScaledInstance(130, 130, Image.SCALE_SMOOTH));
            lblReflector1.setIcon(imgIcon2);

            Image img3 = new ImageIcon(refImg2).getImage();
            ImageIcon imgIcon3 = new ImageIcon(img3.getScaledInstance(130, 130, Image.SCALE_SMOOTH));
            lblReflector2.setIcon(imgIcon3);
            this.repaint();
        } catch (Exception e) {
            System.out.println("Error al cargar Imagenes");
        }
    }

    private void validarInicioSesion() {
        try {
            Validaciones.validarEmail(txtEmail.getText());
            Validaciones.validarPassword(txtPassword.getText());
            if (Cine.validarLoginYCargarSesion(txtEmail.getText(), txtPassword.getText()) == true) {
                Sesion.setEmailLogeado(txtEmail.getText());
                if (Sesion.getTipo().equals("Cliente")) {
                    this.dispose();
                    new MenuCliente(txtEmail.getText()).setVisible(true);
                } else if (Sesion.getTipo().equals("Gerente")) {
                    this.dispose();
                    new MenuGerente().setVisible(true);
                } else if (Sesion.getTipo().equals("Admin")) {
                    this.dispose();
                    new MenuAdmin().setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Email o contraseña incorrecta!");
            }
        } catch (CampoVacioException | EmailException | LongitudPasswordException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblEmail = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblCineNombre = new javax.swing.JLabel();
        lblImagenCine = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblReflector2 = new javax.swing.JLabel();
        lblReflector1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 45, 39));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setBackground(new java.awt.Color(44, 117, 160));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 300, 45));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 300, 45));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email:");
        lblEmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 100, 45));

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("Contraseña:");
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 190, 45));

        lblCineNombre.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 50)); // NOI18N
        lblCineNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblCineNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCineNombre.setText("Magic Cinema\t ");
        jPanel1.add(lblCineNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 270, -1));
        jPanel1.add(lblImagenCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 240, 230));

        btnRegistrarse.setBackground(new java.awt.Color(210, 19, 18));
        btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseMoved(evt);
            }
        });
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseExited(evt);
            }
        });
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 610, -1, 50));

        btnLogin.setBackground(new java.awt.Color(207, 14, 44));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Iniciar Sesion");
        btnLogin.setFocusable(false);
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLoginMouseMoved(evt);
            }
        });
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 240, 50));
        jPanel1.add(lblReflector2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 210, 130, 130));
        jPanel1.add(lblReflector1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1296, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // TODO add your handling code here:
        new RegistroCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        validarInicioSesion();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseMoved
        // TODO add your handling code here:
        btnLogin.setBackground(new Color(138, 0, 21));
    }//GEN-LAST:event_btnLoginMouseMoved

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setBackground(new Color(207, 14, 44));
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseExited
        // TODO add your handling code here:
        btnRegistrarse.setBackground(new Color(210, 19, 18));
    }//GEN-LAST:event_btnRegistrarseMouseExited

    private void btnRegistrarseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseMoved
        // TODO add your handling code here:
        btnRegistrarse.setBackground(new Color(151, 9, 8));
    }//GEN-LAST:event_btnRegistrarseMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Persistencia.leerDatos();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);

            }
        });
        Admin admin = new Admin("rtoresani@gmail.com", "12345678", "Rafael", "Toresani");
        Cliente cliente=new Cliente("dp@gmail.com","12345678","Diego","Pineda");
        Cine.getListaUsuarios().add(admin);
        Cine.getListaUsuarios().add(cliente);
        Persistencia.actualizarUsuarios();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCineNombre;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblEmail;
    private static javax.swing.JLabel lblImagenCine;
    private javax.swing.JLabel lblReflector1;
    private javax.swing.JLabel lblReflector2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
