/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import cine.cinelugar.Cine;
import cine.cinelugar.Funcion;
import cine.cinelugar.Pelicula;
import java.awt.Color;
import java.awt.Image;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;

/**
 *
 * @author horus
 */
public class MenuReserva extends javax.swing.JFrame {

    /**
     * Creates new form MenuReserva
     */
    public MenuReserva() {
        initComponents();
        actualizarListPeliculas();
        actualizarListaFunciones();
        iniciar();
    }
    
    private void actualizarListPeliculas() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        listPeliculas.setModel(model);
        for (Pelicula e : Cine.getListaPeliculas()) {
            if (!e.isBaja()) {
                model.addElement(e.getNombre());
            }
        }
    }
    
    public void iniciar(){
        lblImagen.setHorizontalAlignment(JLabel.CENTER);
        lblImagen.setBorder(new LineBorder(Color.black,2,true));
        try{
            Image img = new ImageIcon(retornaPelicula().getRutaImagen()).getImage();
            ImageIcon imgIcon = new ImageIcon(img.getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH));
            lblImagen.setIcon(imgIcon);
        }catch (Exception e){
            System.out.println("No hay nada :C");
        }  
    }

    private Pelicula retornaPelicula() {
        String str = listPeliculas.getSelectedItem().toString();
        for (Pelicula e : Cine.getListaPeliculas()) {
            if (str.contains(e.getNombre())) {
                return e;
            }
        }
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listFunciones = new javax.swing.JComboBox<>();
        lblFunciones = new javax.swing.JLabel();
        lblPeliculas = new javax.swing.JLabel();
        listPeliculas = new javax.swing.JComboBox<>();
        btnReservar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSelectButaca = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listFuncionesActionPerformed(evt);
            }
        });
        getContentPane().add(listFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 220, 360, 34));

        lblFunciones.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblFunciones.setText("Funciones Disponibles");
        getContentPane().add(lblFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblPeliculas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblPeliculas.setText("Peliculas disponibles");
        getContentPane().add(lblPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        listPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPeliculasActionPerformed(evt);
            }
        });
        getContentPane().add(listPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 222, 34));

        btnReservar.setBackground(new java.awt.Color(102, 255, 51));
        btnReservar.setText("Hacer reserva");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 120, 33));

        btnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 100, 33));

        btnSelectButaca.setText("Seleccionar butaca");
        btnSelectButaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectButacaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectButaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, 35));
        getContentPane().add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 310, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPeliculasActionPerformed
        // TODO add your handling code here:
        iniciar();
        actualizarListaFunciones();
    }//GEN-LAST:event_listPeliculasActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MenuCliente cliente = new MenuCliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSelectButacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectButacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectButacaActionPerformed

    private void listFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listFuncionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listFuncionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuReserva().setVisible(true);
            }
        });
    }
    
    private void actualizarListaFunciones(){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        listFunciones.setModel(model);
        String str = retornaPelicula().getNombre();
        for(Funcion e: Cine.getListaFunciones()){
            if(e.getPelicula().getNombre().equals(str)){
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                model.addElement(e.getNombre() + " | " + format.format(e.getDia()) + " | " + e.getHorario().getHorario());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnSelectButaca;
    private javax.swing.JLabel lblFunciones;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPeliculas;
    private javax.swing.JComboBox<String> listFunciones;
    private javax.swing.JComboBox<String> listPeliculas;
    // End of variables declaration//GEN-END:variables
}
