/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import cine.cinelugar.Cine;
import cine.cinelugar.Pelicula;
import cine.cinelugar.Sala;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import persistencia.Persistencia;

/**
 *
 * @author Diego
 */
public class MenuGerente extends javax.swing.JFrame {

    /**
     * Creates new form MenuGerente
     */
    public MenuGerente() {
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarListPeliculas();
        actualizarListSalas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JLabel();
        btnAgregarPelicula1 = new javax.swing.JLabel();
        listPeliculas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnModificarPelicula = new javax.swing.JLabel();
        btnBajaPelicula = new javax.swing.JLabel();
        lblAgregarSala = new javax.swing.JLabel();
        listSalas = new javax.swing.JComboBox<>();
        lblModificarSala = new javax.swing.JLabel();
        btnBajaSala = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        btnCerrarSesion.setText("Cerrar sesión.");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMousePressed(evt);
            }
        });

        btnAgregarPelicula1.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        btnAgregarPelicula1.setText("Agregar Película");
        btnAgregarPelicula1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregarPelicula1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarPelicula1MousePressed(evt);
            }
        });

        listPeliculas.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        listPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPeliculasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel1.setText("Modificar cartelera");

        btnModificarPelicula.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        btnModificarPelicula.setText("Modificar");
        btnModificarPelicula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificarPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModificarPeliculaMousePressed(evt);
            }
        });

        btnBajaPelicula.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        btnBajaPelicula.setText("Dar baja");
        btnBajaPelicula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBajaPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBajaPeliculaMousePressed(evt);
            }
        });

        lblAgregarSala.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        lblAgregarSala.setText("Agregar Sala");
        lblAgregarSala.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblAgregarSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAgregarSalaMousePressed(evt);
            }
        });

        listSalas.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        listSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSalasActionPerformed(evt);
            }
        });

        lblModificarSala.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        lblModificarSala.setText("Modificar");
        lblModificarSala.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblModificarSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblModificarSalaMousePressed(evt);
            }
        });

        btnBajaSala.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        btnBajaSala.setText("Dar baja");
        btnBajaSala.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBajaSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBajaSalaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPelicula1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAgregarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(listSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblModificarSala)
                                .addGap(18, 18, 18)
                                .addComponent(btnBajaSala))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(listPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarPelicula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBajaPelicula)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnAgregarPelicula1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarPelicula)
                    .addComponent(btnBajaPelicula))
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAgregarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModificarSala)
                            .addComponent(btnBajaSala))
                        .addComponent(listSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMousePressed
        Persistencia.actualizarPeliculas();
        Persistencia.actualizarUsuarios();
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionMousePressed

    private void btnAgregarPelicula1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPelicula1MousePressed
        RegistroPelicula reg = new RegistroPelicula();
        reg.setVisible(true);
        reg.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnAgregarPelicula1MousePressed

    private void btnModificarPeliculaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarPeliculaMousePressed

        for (Pelicula e : Cine.getListaPeliculas()) {
            if (e.getNombre().equals(listPeliculas.getSelectedItem())) {
                this.dispose();
                ModificarPelicula mod = new ModificarPelicula(e);
                mod.setVisible(true);
                mod.setLocationRelativeTo(null);
            }
        }
        //btnModificarPelicula mod = new ModificarPelicula()
    }//GEN-LAST:event_btnModificarPeliculaMousePressed

    private void btnBajaPeliculaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBajaPeliculaMousePressed
        int option = JOptionPane.showConfirmDialog(null, "¿Desea dar de baja la película?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            String nombre = listSalas.getSelectedItem().toString();
            if (listPeliculas.getSelectedItem() != null) {
            for (int i = 0; i < Cine.getListaPeliculas().size(); i++) {
                if (Cine.getListaPeliculas().get(i).getNombre().equals(listPeliculas.getSelectedItem())) {
                    Cine.getListaPeliculas().remove(i);
                }
            }
        }
        actualizarListPeliculas();
        }
    }//GEN-LAST:event_btnBajaPeliculaMousePressed

    private void lblAgregarSalaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarSalaMousePressed
        // TODO add your handling code here:
        new CreacionSala().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAgregarSalaMousePressed

    private void lblModificarSalaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarSalaMousePressed
        // TODO add your handling code here:
        for (Sala e : Cine.getListaSalas()) {
            if (e.getNombre().equals(listSalas.getSelectedItem())) {
                this.dispose();
                ModificarSala algo=new ModificarSala(e);
                algo.setVisible(true);
            }
        }
    }//GEN-LAST:event_lblModificarSalaMousePressed

    private void btnBajaSalaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBajaSalaMousePressed
        int option = JOptionPane.showConfirmDialog(null, "¿Desea dar de baja la sala?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            String nombre = listSalas.getSelectedItem().toString();
            for (int i = 0; i < Cine.getListaSalas().size(); i++) {
                for (Sala sala : Cine.getListaSalas()) {
                    if (sala.getNombre().equals(nombre)) {
                        Cine.getListaSalas().remove(i);
                    }
                }
            }
            actualizarSalas();
        }
    }//GEN-LAST:event_btnBajaSalaMousePressed

    private void listPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPeliculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listPeliculasActionPerformed

    private void listSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listSalasActionPerformed

    private void actualizarListPeliculas() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        listPeliculas.setModel(model);
        for (Pelicula e : Cine.getListaPeliculas()) {
            if (!e.isBaja()) {
                model.addElement(e.getNombre());
            }
        }
    }

    private void actualizarListSalas() {
        DefaultComboBoxModel<String> model2 = new DefaultComboBoxModel<>();
        listSalas.setModel(model2);
        for (Sala e : Cine.getListaSalas()) {

            model2.addElement(e.getNombre());

        }
    }
    private void actualizarSalas() {
        DefaultComboBoxModel<String> model2 = new DefaultComboBoxModel<>();
        listSalas.setModel(model2);
        for (Sala e : Cine.getListaSalas()) {
            if (!e.getBaja()) {
                model2.addElement(e.getNombre());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAgregarPelicula1;
    private javax.swing.JLabel btnBajaPelicula;
    private javax.swing.JLabel btnBajaSala;
    private javax.swing.JLabel btnCerrarSesion;
    private javax.swing.JLabel btnModificarPelicula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgregarSala;
    private javax.swing.JLabel lblModificarSala;
    private javax.swing.JComboBox<String> listPeliculas;
    private javax.swing.JComboBox<String> listSalas;
    // End of variables declaration//GEN-END:variables
}
