/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import cine.cinelugar.Cine;
import cine.cinelugar.Pelicula;
import cine.cinelugar.Sala;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import persistencia.Persistencia;

/**
 *
 * @author Diego
 */
public class MenuGerente extends javax.swing.JFrame {

    /**
     * Creates new form MenuGerente
     */
    public MenuGerente() {
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarListPeliculas();
        actualizarSalas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnCrearFuncion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        listPeliculas = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        btnAgregarPelicula = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btnBajaPelicula = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnModPelicula = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        listSalas = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        btnModSala = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        btnBajaSala = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnAgregarSal = new javax.swing.JLabel();
        lblTituloRegistrar1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(9, 35, 52));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(170, 34, 45));

        btnExit.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(216, 220, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("CERRAR SESION");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 150, 45));

        jPanel4.setBackground(new java.awt.Color(170, 34, 45));

        btnCrearFuncion.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnCrearFuncion.setForeground(new java.awt.Color(216, 220, 255));
        btnCrearFuncion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrearFuncion.setText("Crear funcion");
        btnCrearFuncion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearFuncionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearFuncionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCrearFuncionMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrearFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrearFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 660, 160, 45));

        jPanel2.setBackground(new java.awt.Color(20, 71, 103));

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modificaciones Peliculas");

        listPeliculas.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(9, 35, 52));

        btnAgregarPelicula.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnAgregarPelicula.setForeground(new java.awt.Color(216, 220, 255));
        btnAgregarPelicula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregarPelicula.setText("Agregar Película");
        btnAgregarPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarPeliculaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarPeliculaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarPeliculaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(170, 34, 45));

        btnBajaPelicula.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnBajaPelicula.setForeground(new java.awt.Color(216, 220, 255));
        btnBajaPelicula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBajaPelicula.setText("Dar de baja");
        btnBajaPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBajaPeliculaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBajaPeliculaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBajaPeliculaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBajaPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBajaPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(9, 35, 52));

        btnModPelicula.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnModPelicula.setForeground(new java.awt.Color(216, 220, 255));
        btnModPelicula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnModPelicula.setText("Modificar");
        btnModPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModPeliculaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModPeliculaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModPeliculaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listPeliculas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(listPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 426, 540));

        jPanel5.setBackground(new java.awt.Color(20, 71, 103));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modificaciones Sala");

        listSalas.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N

        jPanel10.setBackground(new java.awt.Color(9, 35, 52));

        btnModSala.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnModSala.setForeground(new java.awt.Color(216, 220, 255));
        btnModSala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnModSala.setText("Modificar");
        btnModSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModSalaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModSalaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModSalaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModSala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModSala, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(170, 34, 45));

        btnBajaSala.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnBajaSala.setForeground(new java.awt.Color(216, 220, 255));
        btnBajaSala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBajaSala.setText("Dar de baja");
        btnBajaSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBajaSalaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBajaSalaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBajaSalaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnBajaSala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnBajaSala, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(9, 35, 52));

        btnAgregarSal.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnAgregarSal.setForeground(new java.awt.Color(216, 220, 255));
        btnAgregarSal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregarSal.setText("Agregar Sala");
        btnAgregarSal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarSalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarSalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarSalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarSal, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregarSal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 119, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(listSalas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(listSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 100, 426, 540));

        lblTituloRegistrar1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        lblTituloRegistrar1.setForeground(new java.awt.Color(216, 220, 255));
        lblTituloRegistrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRegistrar1.setText("MENU GERENTE");
        jPanel1.add(lblTituloRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 320, 60));

        jPanel9.setBackground(new java.awt.Color(170, 34, 45));

        btnSalir.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(216, 220, 255));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.setText("X");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(204, 40, 54));
        btnExit.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(170, 34, 45));
        btnExit.setForeground(new Color(216, 220, 255));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        // TODO add your handling code here:
        Persistencia.actualizarPeliculas();
        Persistencia.actualizarUsuarios();
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnExitMousePressed

    private void btnCrearFuncionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearFuncionMouseEntered
        // TODO add your handling code here:
        jPanel4.setBackground(new Color(204, 40, 54));
        btnExit.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnCrearFuncionMouseEntered

    private void btnCrearFuncionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearFuncionMouseExited
        // TODO add your handling code here:
        jPanel4.setBackground(new Color(170, 34, 45));
        btnExit.setForeground(new Color(216, 220, 255));
    }//GEN-LAST:event_btnCrearFuncionMouseExited

    private void btnCrearFuncionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearFuncionMousePressed
        // TODO add your handling code here:
        RegistroFuncion reg = new RegistroFuncion();
        reg.setVisible(true);
        reg.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCrearFuncionMousePressed

    private void btnAgregarPeliculaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPeliculaMouseEntered
        jPanel6.setBackground(new Color(12, 47, 69));
        btnAgregarPelicula.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnAgregarPeliculaMouseEntered

    private void btnAgregarPeliculaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPeliculaMouseExited
        // TODO add your handling code here:
        jPanel6.setBackground(new Color(9, 36, 52));
        btnAgregarPelicula.setForeground(new Color(216, 220, 255));
    }//GEN-LAST:event_btnAgregarPeliculaMouseExited

    private void btnAgregarPeliculaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPeliculaMousePressed
        // TODO add your handling code here:
        RegistroPelicula reg = new RegistroPelicula();
        reg.setVisible(true);
        reg.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnAgregarPeliculaMousePressed

    private void btnBajaPeliculaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBajaPeliculaMouseEntered
        // TODO add your handling code here:
        jPanel11.setBackground(new Color(204, 40, 54));
        btnBajaPelicula.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnBajaPeliculaMouseEntered

    private void btnBajaPeliculaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBajaPeliculaMouseExited
        // TODO add your handling code here:
        jPanel11.setBackground(new Color(170, 34, 45));
        btnBajaPelicula.setForeground(new Color(216, 220, 255));
    }//GEN-LAST:event_btnBajaPeliculaMouseExited

    private void btnBajaPeliculaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBajaPeliculaMousePressed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "¿Desea dar de baja la película?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            if (listPeliculas.getSelectedItem() != null) {
                for (int i = 0; i < Cine.getListaPeliculas().size(); i++) {
                    if (Cine.getListaPeliculas().get(i).getNombre().equals(listPeliculas.getSelectedItem())) {
                        Cine.getListaPeliculas().remove(i);
                    }
                }
            }
            actualizarListPeliculas();
        }
    }//GEN-LAST:event_btnBajaPeliculaMousePressed

    private void btnModPeliculaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModPeliculaMouseEntered
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(12, 47, 69));
        btnAgregarPelicula.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnModPeliculaMouseEntered

    private void btnModPeliculaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModPeliculaMouseExited
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(9, 36, 52));
        btnAgregarPelicula.setForeground(new Color(216, 220, 255));
    }//GEN-LAST:event_btnModPeliculaMouseExited

    private void btnModPeliculaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModPeliculaMousePressed
        // TODO add your handling code here:
        for (Pelicula pelicula : Cine.getListaPeliculas()) {
            if (pelicula.getNombre().equals(listPeliculas.getSelectedItem())) {
                this.dispose();
                ModificarPelicula mod = new ModificarPelicula(pelicula);
                mod.setVisible(true);
                mod.setLocationRelativeTo(null);
            }
        }
    }//GEN-LAST:event_btnModPeliculaMousePressed

    private void btnModSalaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModSalaMouseEntered
        // TODO add your handling code here:
        jPanel10.setBackground(new Color(12, 47, 69));
        btnAgregarPelicula.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnModSalaMouseEntered

    private void btnModSalaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModSalaMouseExited
        // TODO add your handling code here:
        jPanel10.setBackground(new Color(9, 36, 52));
        btnAgregarPelicula.setForeground(new Color(216, 220, 255));
    }//GEN-LAST:event_btnModSalaMouseExited

    private void btnModSalaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModSalaMousePressed
        // TODO add your handling code here:
        for (Sala sala : Cine.getListaSalas()) {
            if (sala.getNombre().equals(listSalas.getSelectedItem())) {
                this.dispose();
                ModificarSala algo = new ModificarSala(sala);
                algo.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnModSalaMousePressed

    private void btnBajaSalaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBajaSalaMouseEntered
        // TODO add your handling code here:
        jPanel13.setBackground(new Color(204, 40, 54));
        btnBajaPelicula.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnBajaSalaMouseEntered

    private void btnBajaSalaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBajaSalaMouseExited
        // TODO add your handling code here:
        jPanel13.setBackground(new Color(170, 34, 45));
        btnBajaPelicula.setForeground(new Color(216, 220, 255));
    }//GEN-LAST:event_btnBajaSalaMouseExited

    private void btnBajaSalaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBajaSalaMousePressed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "¿Desea dar de baja la sala?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            String nombre = listSalas.getSelectedItem().toString();
            for (int i = Cine.getListaSalas().size() - 1; i >= 0; i--) {
                Sala sala = Cine.getListaSalas().get(i);
                if (sala.getNombre().equals(nombre)) {
                    Cine.getListaSalas().remove(i);
                }
            }
            actualizarSalasNombre();
            actualizarSalas();
            Persistencia.actualizarSalas();
        }
    }//GEN-LAST:event_btnBajaSalaMousePressed

    private void btnAgregarSalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarSalMouseEntered
        // TODO add your handling code here:
        jPanel7.setBackground(new Color(12, 47, 69));
        btnAgregarPelicula.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnAgregarSalMouseEntered

    private void btnAgregarSalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarSalMouseExited
        // TODO add your handling code here:
        jPanel7.setBackground(new Color(9, 36, 52));
        btnAgregarPelicula.setForeground(new Color(216, 220, 255));
    }//GEN-LAST:event_btnAgregarSalMouseExited

    private void btnAgregarSalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarSalMousePressed
        // TODO add your handling code here:
        new CreacionSala().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarSalMousePressed

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // TODO add your handling code here:
        jPanel9.setBackground(new Color(204, 40, 54));
        btnSalir.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        // TODO add your handling code here:
        jPanel9.setBackground(new Color(170, 34, 45));
        btnSalir.setForeground(new Color(216, 220, 255));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMousePressed

    private void actualizarListPeliculas() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        listPeliculas.setModel(model);
        for (Pelicula pelicula : Cine.getListaPeliculas()) {
            if (!pelicula.isBaja()) {
                model.addElement(pelicula.getNombre());
            }
        }
    }

    private void actualizarSalas() {
        DefaultComboBoxModel<String> model2 = new DefaultComboBoxModel<>();
        listSalas.setModel(model2);
        for (Sala sala : Cine.getListaSalas()) {
             model2.addElement(sala.getNombre());
        }
    }

    private void actualizarSalasNombre() {
        for (int i = Cine.getListaSalas().size() - 1; i >= 0; i--) {
            Sala sala = Cine.getListaSalas().get(i);
            sala.setNombre("Sala " + (i+1));
            sala.setId(i+1);
        }
        actualizarSalas();
        Persistencia.actualizarSalas();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAgregarPelicula;
    private javax.swing.JLabel btnAgregarSal;
    private javax.swing.JLabel btnBajaPelicula;
    private javax.swing.JLabel btnBajaSala;
    private javax.swing.JLabel btnCrearFuncion;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnModPelicula;
    private javax.swing.JLabel btnModSala;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblTituloRegistrar1;
    private javax.swing.JComboBox<String> listPeliculas;
    private javax.swing.JComboBox<String> listSalas;
    // End of variables declaration//GEN-END:variables
}
