/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import cine.cinelugar.Cine;
import cine.cinelugar.Sala;
import cine.user.Sesion;
import excepciones.CampoVacioException;
import excepciones.SoloNumerosException;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import persistencia.Persistencia;

/**
 *
 * @author Diego
 */
public class ModificarSala extends javax.swing.JFrame {

    
    
    int filas =10;
    int columnas =20;
    int largoBoton=50;
    int anchoBoton =25;
    int ejeX=20;
    int ejeY=20;
    public Sala sala=new Sala(filas, columnas);
    /**
     * Creates new form ModificarSala
     */
    public ModificarSala(Sala sala) {
        initComponents();
        this.sala=sala;
        setLocationRelativeTo(null);
        botones();
        lblNombreSala.setText(sala.getNombre());
    }

    public ModificarSala() {
    }
    
    
    
    
    
    
    public JToggleButton [][] jtBotones =new JToggleButton[filas][columnas];
    
    public void botones(){
        jtBotones= new JToggleButton[filas][columnas];
        for(int i=0;i<filas; i++){
            for(int j=0;j<columnas;j++){
                jtBotones[i][j]= new JToggleButton();
                jtBotones[i][j].setBounds(ejeX,ejeY,largoBoton,anchoBoton);
                //jtBotones[i][j].setFont hay que hacer esto
                AccionBotones accion=new AccionBotones();
                jtBotones[i][j].addActionListener(accion);
                if(sala.getButacas()[i][j].isExiste()==true)
                {
                    jtBotones[i][j].setSelected(true);
                    jtBotones[i][j].setBackground(Color.RED);
                }else{
                    jtBotones[i][j].setBackground(Color.BLUE);
                }
                
                
                
                
                pnlBotones.add(jtBotones[i][j]);
                ejeX+=55;//separacion ejeX
                
            }
            ejeX=20; //reseteo la poss inicial
            ejeY+=30; //separacion ejeY
        }
    }
    
    public class AccionBotones implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            for(int i=0; i<filas; i++){
                for(int j=0;j<columnas;j++){
                    if(e.getSource().equals(jtBotones[i][j])){
                        if(jtBotones[i][j].isSelected()){
                            jtBotones[i][j].setBackground(Color.RED);
                            sala.getButacas()[i][j].setExiste(true);
                            sala.setCapacidad(sala.getCapacidad()+1);
                            //aumentar contador para comparar con cantidad de boletos
                        }else{
                            jtBotones[i][j].setBackground(Color.BLUE);
                            sala.getButacas()[i][j].setExiste(false);
                            sala.setCapacidad(sala.getCapacidad()-1);
                            //disminuir contador
                        }
                    }
                }
            }
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        lblVolver = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();
        lblNombreSala = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 124, 1240, 460));

        lblVolver.setText("Volver");
        lblVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVolverMousePressed(evt);
            }
        });
        jPanel1.add(lblVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 20));

        lblModificar.setText("Modificar");
        lblModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblModificarMousePressed(evt);
            }
        });
        jPanel1.add(lblModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 610, 100, 40));

        lblNombreSala.setText("jLabel1");
        jPanel1.add(lblNombreSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMousePressed
        // TODO add your handling code here:
        if (Sesion.getTipo().equals("Admin")) {
            this.dispose();
            MenuAdmin admin = new MenuAdmin();
            admin.setVisible(true);
        } else if (Sesion.getTipo().equals("Gerente")) {
            this.dispose();
            MenuGerente gerente = new MenuGerente();
            gerente.setVisible(true);
        }
    }//GEN-LAST:event_lblVolverMousePressed

    private void lblModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMousePressed
        // TODO add your handling code here:
        
        String nombreviejo=sala.getNombre();
        if (sala.getCapacidad()>0){
            boolean flag=false;
        for (int i = 0; i < Cine.getListaSalas().size() && flag == false; i++) {
                if (Cine.getListaSalas().get(i).getNombre().equals(nombreviejo)) {
                    Cine.getListaSalas().set(i, sala);
                    flag = true;
                }
            }
            Persistencia.actualizarSalas(); 
            JOptionPane.showMessageDialog(null, "Sala modificada exitosamente!" + sala.toString());
            lblVolverMousePressed(evt);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "La sala debe tener 1 asiento o mas!" + sala.toString());
        }
        

        
        
    }//GEN-LAST:event_lblModificarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ModificarSala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblNombreSala;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JPanel pnlBotones;
    // End of variables declaration//GEN-END:variables
}
