/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import cine.cinelugar.Cine;
import cine.cinelugar.Sala;
import cine.user.Sesion;
import excepciones.CampoVacioException;
import excepciones.SoloNumerosException;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import persistencia.Persistencia;

/**
 *
 * @author Diego
 */
public class ModificarSala extends javax.swing.JFrame {

    int largoBoton = 50;
    int anchoBoton = 25;
    int ejeX = 200;
    int ejeY = 70;
    public Sala sala = new Sala();

    /**
     * Creates new form ModificarSala
     */
    public ModificarSala(Sala sala) {
        initComponents();
        this.sala = sala;
        setLocationRelativeTo(null);
        botones();
        lblNombreSala.setText(sala.getNombre());
        if (sala.getAtmos()) {
            checkAtmos.setSelected(true);
        }
    }

    public ModificarSala() {
    }

    public JToggleButton[][] jtBotones = new JToggleButton[sala.getFilas()][sala.getColumnas()];

    public void botones() {
        jtBotones = new JToggleButton[sala.getFilas()][sala.getColumnas()];
        for (int i = 0; i < sala.getFilas(); i++) {
            for (int j = 0; j < sala.getColumnas(); j++) {
                jtBotones[i][j] = new JToggleButton();
                jtBotones[i][j].setBounds(ejeX, ejeY, largoBoton, anchoBoton);
                //jtBotones[i][j].setFont hay que hacer esto
                AccionBotones accion = new AccionBotones();
                jtBotones[i][j].addActionListener(accion);
                if (sala.getButacas()[i][j].isExiste() == true) {
                    jtBotones[i][j].setSelected(true);
                    jtBotones[i][j].setBackground(Color.RED);
                } else {
                    jtBotones[i][j].setBackground(Color.BLUE);
                }

                pnlBotones.add(jtBotones[i][j]);
                ejeX += 55;//separacion ejeX

            }
            ejeX = 200; //reseteo la poss inicial
            ejeY += 30; //separacion ejeY
        }
    }

    public class AccionBotones implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            for (int i = 0; i < sala.getFilas(); i++) {
                for (int j = 0; j < sala.getColumnas(); j++) {
                    if (e.getSource().equals(jtBotones[i][j])) {
                        if (jtBotones[i][j].isSelected()) {
                            jtBotones[i][j].setBackground(Color.RED);
                            sala.getButacas()[i][j].setExiste(true);
                            sala.setCapacidad(sala.getCapacidad() + 1);
                            //aumentar contador para comparar con cantidad de boletos
                        } else {
                            jtBotones[i][j].setBackground(Color.BLUE);
                            sala.getButacas()[i][j].setExiste(false);
                            sala.setCapacidad(sala.getCapacidad() - 1);
                            //disminuir contador
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        lblNombreSala = new javax.swing.JLabel();
        checkAtmos = new javax.swing.JCheckBox();
        btnVolver = new javax.swing.JButton();
        btnModificarSala = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 45, 39));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1260, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1240, 430));

        lblNombreSala.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblNombreSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        checkAtmos.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        checkAtmos.setForeground(new java.awt.Color(255, 255, 255));
        checkAtmos.setText("ATMOS");
        checkAtmos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAtmosActionPerformed(evt);
            }
        });
        jPanel1.add(checkAtmos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 110, 40));

        btnVolver.setBackground(new java.awt.Color(255, 0, 30));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Atras");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 40));

        btnModificarSala.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModificarSala.setText("Modificar Sala");
        btnModificarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarSalaActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkAtmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAtmosActionPerformed

    }//GEN-LAST:event_checkAtmosActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        if (Sesion.getTipo().equals("Admin")) {
            this.dispose();
            MenuAdmin admin = new MenuAdmin();
            admin.setVisible(true);
        } else if (Sesion.getTipo().equals("Gerente")) {
            this.dispose();
            MenuGerente gerente = new MenuGerente();
            gerente.setVisible(true);
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnModificarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarSalaActionPerformed
        // TODO add your handling code here:
        String nombreviejo = sala.getNombre();
        if (sala.getCapacidad() > 0) {
            if (checkAtmos.isSelected()) {
                sala.setAtmos(true);
            } else {
                sala.setAtmos(false);
            }
            boolean flag = false;
            for (int i = 0; i < Cine.getListaSalas().size() && flag == false; i++) {
                if (Cine.getListaSalas().get(i).getNombre().equals(nombreviejo)) {
                    Cine.getListaSalas().set(i, sala);
                    flag = true;
                }
            }
            Persistencia.actualizarSalas();
            JOptionPane.showMessageDialog(null, "Sala modificada exitosamente!" + sala.toString());
            btnVolverActionPerformed(evt);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "La sala debe tener 1 asiento o mas!" + sala.toString());
        }
    }//GEN-LAST:event_btnModificarSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ModificarSala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarSala;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox checkAtmos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNombreSala;
    private javax.swing.JPanel pnlBotones;
    // End of variables declaration//GEN-END:variables
}
