/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import cine.cinelugar.Funcion;
import cine.user.Sesion;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JToggleButton;

/**
 *
 * @author Hoid
 */
public class ReservaButaca extends javax.swing.JFrame {

    private Funcion funcion;
    private int filas;
    private int columnas;
    int largoBoton = 50;
    int anchoBoton = 25;
    int ejeX = 20;
    int ejeY = 20;

    /**
     * Creates new form ReservaButaca
     */
    public ReservaButaca(Funcion e) {
        this.funcion = e;
        this.filas=e.getSala().getFilas();
        this.columnas=e.getSala().getColumnas();
        System.out.println(filas + " " + columnas);
        botones();
        initComponents();
    }

    public ReservaButaca() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        lblVolver = new javax.swing.JLabel();
        btnReservar = new javax.swing.JLabel();
        lblNombreSala = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 124, 1240, 460));

        lblVolver.setText("Volver");
        lblVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVolverMousePressed(evt);
            }
        });
        jPanel1.add(lblVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 20));

        btnReservar.setText("Reserva");
        btnReservar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReservarMousePressed(evt);
            }
        });
        jPanel1.add(btnReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 610, 100, 40));

        lblNombreSala.setText("jLabel1");
        jPanel1.add(lblNombreSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMousePressed
        // TODO add your handling code here:
        MenuReserva cliente = new MenuReserva();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblVolverMousePressed

    public JToggleButton[][] jtBotones = new JToggleButton[filas][columnas];

    public void botones() {
        jtBotones = new JToggleButton[filas][columnas];
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                jtBotones[i][j] = new JToggleButton();
                jtBotones[i][j].setBounds(ejeX, ejeY, largoBoton, anchoBoton);
                
                AccionBotones accion = new AccionBotones();
                jtBotones[i][j].addActionListener(accion);
                if (funcion.getSala().getButacas()[i][j].isExiste() == true) {
                    jtBotones[i][j].setSelected(true);
                    jtBotones[i][j].setBackground(Color.RED);
                } else {
                    jtBotones[i][j].setBackground(Color.BLUE);
                }

                pnlBotones.add(jtBotones[i][j]);
                ejeX += 55;//separacion ejeX

            }
            ejeX = 20; //reseteo la poss inicial
            ejeY += 30; //separacion ejeY
        }
    }

    public class AccionBotones implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            for (int i = 0; i < funcion.getSala().getFilas(); i++) {
                for (int j = 0; j < funcion.getSala().getColumnas(); j++) {
                    if (e.getSource().equals(jtBotones[i][j])) {
                        if (jtBotones[i][j].isSelected()) {
                            jtBotones[i][j].setBackground(Color.RED);
                            funcion.getSala().getButacas()[i][j].setExiste(true);
                            funcion.getSala().setCapacidad(funcion.getSala().getCapacidad() + 1);
                            //aumentar contador para comparar con cantidad de boletos
                        } else {
                            jtBotones[i][j].setBackground(Color.BLUE);
                            funcion.getSala().getButacas()[i][j].setExiste(false);
                            funcion.getSala().setCapacidad(funcion.getSala().getCapacidad() - 1);
                            //disminuir contador
                        }
                    }
                }
            }
        }
    }


    private void btnReservarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservarMousePressed
        // TODO add your handling code here:
/*
        String nombreviejo=sala.getNombre();
        if (sala.getCapacidad()>0){
            if(checkAtmos.isSelected()){
                sala.setAtmos(true);
            }else{
                sala.setAtmos(false);
            }
            boolean flag=false;
            for (int i = 0; i < Cine.getListaSalas().size() && flag == false; i++) {
                if (Cine.getListaSalas().get(i).getNombre().equals(nombreviejo)) {
                    Cine.getListaSalas().set(i, sala);
                    flag = true;
                }
            }
            Persistencia.actualizarSalas();
            JOptionPane.showMessageDialog(null, "Sala modificada exitosamente!" + sala.toString());
            lblVolverMousePressed(evt);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "La sala debe tener 1 asiento o mas!" + sala.toString());
        }
         */
    }//GEN-LAST:event_btnReservarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaButaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaButaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaButaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaButaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservaButaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnReservar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNombreSala;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JPanel pnlBotones;
    // End of variables declaration//GEN-END:variables
}
